---
- name: Add repository CRI-O
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
      dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
    - url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.24:1.24.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.24:1.24.1.repo
      dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.24:1.24.1.repo    

- name: Install CRI-O
  dnf:
    name: cri-o
    state: latest

- name: Enable kernel modules for CRI-O
  copy:
    dest: /etc/modules-load.d/crio.conf
    content: |
      overlay
      br_netfilter

- name: Start CRI-O
  service:
    name: crio
    state: started
    enabled: yes