- name: Add Kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes yum repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kubelet kubeadm kubectl

- name: Install Kubernetes
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    disable_excludes: kubernetes

- name: Start kubelet
  service:
    name: kubelet
    state: started
    enabled: yes