apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: app-pacman
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/shared
    server: 10.0.2.6