apiVersion: v1
kind: Service
metadata:
  name: pacman
  labels:
    name: pacman
  namespace: app-pacman
spec:
  type: NodePort
  selector:
    name: pacman
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32593
      protocol: TCP

