---
  - name: Create temp directory 
    file:
      path: "{{ temp_path }}"
      state: directory

  - name: Get the files needed for deployment
    copy:
      src: ../files/{{ item }}.yaml
      dest: "{{ temp_path }}"
    with_items:
      - mongodb-deployment
      - mongodb-pv
      - mongodb-pvc
      - mongodb-service
      - pacman-deployment
      - pacman-service

  - name: Change the IP of mongodb-pv
    shell: |
      sed -i "19s/.*/    server: {{ hostvars[item].private_ip }}/" {{ temp_path }}/mongodb-pv.yaml
    with_items: 
        - "{{ groups['nfs'] }}"
  
  - name: Install pre-requisites for k8s module
    pip:
      name:
        - pyyaml
        - kubernetes 
        - jsonpatch

  - name: Create the namespace 
    k8s:
      api_version: v1
      name: app-pacman
      kind: Namespace
      state: present
    become: true
    become_user: "{{ ansible_user }}"