---
  - name: Create persistent volume for our MongoDB to persist the database
    k8s:
      state: present
      src: "{{ temp_path }}/mongodb-pv.yaml"
    become: true
    become_user: "{{ ansible_user }}"
