---
  - name: Create persistent volume claim for our MongoDB to persist the database
    k8s:
      state: present
      src: "{{ temp_path }}/mongodb-pvc.yaml"
    become: true
    become_user: "{{ ansible_user }}"