---
  - name: Create a mongo DNS entry
    k8s:
      state: present
      src: "{{ temp_path }}/mongodb-service.yaml"
    become: true
    become_user: "{{ ansible_user }}"

  - name: Create the MongoDB deployment
    k8s:
      state: present
      src: "{{ temp_path }}/mongodb-deployment.yaml"
    become: true
    become_user: "{{ ansible_user }}"