---
  - name: Create a mongo DNS entry
    shell: | 
      kubectl create -f {{ temp_path }}/mongodb-service.yaml
    become: false

  - name: Create the MongoDB deployment
    shell: | 
      kubectl create -f {{ temp_path }}/mongodb-deployment.yaml
    become: false

  # - name: Scale the deployment
  #   shell: | 
  #    kubectl scale deployment.apps/mongo --replicas=1
  #   become: false
