---
  - name: Creates the service to access the application
    shell: | 
      kubectl create -f {{ temp_path }}/pacman-service.yaml
    become: false
  
  - name: Ceate the Pac-Man deployment.
    shell: | 
      kubectl create -f {{ temp_path }}/pacman-deployment.yaml
    become: false

 #  - name: Scale the deployment
 #    shell: | 
 #      kubectl scale deployment.apps/pacman --replicas=2
 #    become: false
