---
  - name: Ceate the Pac-Man deployment.
    k8s:
      state: present
      src: "{{ temp_path }}/pacman-deployment.yaml"
    become: true
    become_user: "{{ ansible_user }}"
  
  - name: Creates the service to access the application
    k8s:
      state: present
      src: "{{ temp_path }}/pacman-service.yaml"
    become: true
    become_user: "{{ ansible_user }}"