---
  - name: Pulling images for Kubernetes cluster
    command: kubeadm config images pull

  - name: Ininitalization kubeadm
    command: kubeadm init --pod-network-cidr=10.0.0.0/16

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    delegate_to: localhost
    copy:
      content: "{{ join_command.stdout_lines[0] }}"
      dest: "./join-command"
      mode: 0755
    become: false

  - name: Create directory .kube
    file: 
      path: /home/{{ ansible_user }}/.kube
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0755

  - name: Copy admin.conf 
    copy:
      remote_src: yes
      src: /etc/kubernetes/admin.conf 
      dest: /home/{{ ansible_user }}/.kube/config
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0755