---
  - name: Allow traffic on the firewall of the master and workers
    firewalld:
      port: 8285-8472/udp
      permanent: yes
      state: enabled

  - name: Reload service firewalld
    systemd:
      name: firewalld
      state: reloaded
  
  - name: Apply the definition of the network policies in the master node
    command: kubectl apply -f https://docs.projectcalico.org/manifests/canal.yaml
  
  - name: Reboot node master 
    reboot:
    