---
  - name: Execution of the common tasks
    hosts: all
    become: yes
    gather_facts: yes
    roles:
      - common
 
  - name: Execution of the masters tasks
    hosts: master
    become: yes
    gather_facts: no
    roles:
      - master

  - name: Execution of the workers tasks
    hosts: workers
    become: yes
    gather_facts: no
    roles:
      - workers

  - name: Execution of the nfs tasks
    hosts: nfs
    become: yes
    gather_facts: no
    roles:
      - nfs

  - name: Execution of the app tasks
    hosts: master
    become: yes
    gather_facts: no
    roles:
      - app